# Data Driven insights for a new movie studio
PHASE 2  PROJECT

**Authors: Group 4 Members**
- Emma Kahoro
- John Gitu
- Ryan Ngigi
- Matthews Kaunda
- Brian Koome

**Date:**  10/11/2015

## Business Problem
The company is launching new movie studio but know nothing about film production. 
They are exploring what types of films are currently doing the best at the box office. Then translate those findings into actionable insights that the head of your company's new movie studio can use to help decide what type of films to create.

## Objective
Determine the best performing genres and studios and their financial outcome to determine the investment and production decisions.

## Research Objectives
1. To determine the best performing genres according to ratings
2. To determine the best performing genre based on popularity(num of votes)
3. To analyze film performance across studios, years and domestic versus international markets

### Plan
1. Obtain the data from github
2. Load data
3. Clean the columns of interest
4. Perform Data Analysis
5. Draw evidence based solutions

In [9]:
# import libraries
import pandas as pd
import sqlite3
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### 1.0 Data Loading and Cleaning
Loading the datasets, data understanding and cleaning the data for analysis

The data of interest is the im.db database and the bom.movie_gross.csv dataset

In [10]:
# Loading the box office mojo dataset
bom = pd.read_csv("Data/bom.movie_gross.csv")
bom.head()

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010

In [11]:
bom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3387 non-null   object
 1   studio          3382 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   foreign_gross   2037 non-null   object
 4   year            3387 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB

In [12]:
# Change foreign gross column to numeric
bom['foreign_gross'] = pd.to_numeric(bom['foreign_gross'], errors='coerce')

In [13]:
# Missing Values
bom.isna().sum()

title                0
studio               5
domestic_gross      28
foreign_gross     1355
year                 0
dtype: int64

In [14]:
x= bom[bom['domestic_gross'].isna() & bom['foreign_gross'].isna()]
print(x)

Empty DataFrame
Columns: [title, studio, domestic_gross, foreign_gross, year]
Index: []

In [15]:
# Drop the rows with missing values in domestic gross and studio
bom = bom.dropna(subset=['domestic_gross', 'studio'])

In [16]:
# Fill missing values in foreign gross with median
bom['foreign_gross'].fillna(bom['foreign_gross'].median(), inplace=True)

In [17]:
bom['studio'].value_counts().head(10)

studio
IFC      166
Uni.     147
WB       140
Magn.    136
Fox      136
SPC      123
Sony     109
BV       106
LGF      102
Par.     101
Name: count, dtype: int64

In [18]:
bom.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3356 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3356 non-null   object
 1   studio          3356 non-null   object
 2   domestic_gross  3356 non-null   float64
 3   foreign_gross   3356 non-null   float64
 4   year            3356 non-null   int64
dtypes: float64(2), int64(1), object(2)
memory usage: 157.3+ KB

In [19]:
# Loading the SQL database
# Connect to the database
conn = sqlite3.connect("Data/im.db")

# Create cursor to execute sql commands
cur = conn.cursor()

In [20]:
# List all table names in the database
pd.read_sql("""SELECT name
            FROM sqlite_master
            WHERE type = 'table';
""",conn)

Empty DataFrame
Columns: [name]
Index: []

In [21]:
# movie_basics table
pd.read_sql(""" 
        SELECT *
        FROM movie_basics
        LIMIT 5;      
""",conn)

DatabaseError: Execution failed on sql '
        SELECT *
        FROM movie_basics
        LIMIT 5;
': no such table: movie_basics

In [ ]:
# Check for missing values in key columns

pd.read_sql("""
    SELECT 
        SUM(CASE WHEN primary_title IS NULL THEN 1 ELSE 0 END) AS missing_title,
        SUM(CASE WHEN start_year IS NULL THEN 1 ELSE 0 END) AS missing_year,
        SUM(CASE WHEN runtime_minutes IS NULL THEN 1 ELSE 0 END) AS missing_runtime,
        SUM(CASE WHEN genres IS NULL THEN 1 ELSE 0 END) AS missing_genre
    FROM movie_basics;
""", conn)

In [ ]:
# Check for duplicates by 'movie_id' 
pd.read_sql("""
    SELECT movie_id, COUNT(*) AS count
    FROM movie_basics
    GROUP BY movie_id
    HAVING COUNT(*) > 1;
""", conn)

In [ ]:
# Check Numeric ranges
pd.read_sql("""
    SELECT 
        MIN(start_year) AS min_year,
        MAX(start_year) AS max_year,
        MIN(runtime_minutes) AS min_runtime,
        MAX(runtime_minutes) AS max_runtime
    FROM movie_basics;
""", conn)

In [ ]:
cur.execute("""
            DELETE FROM movie_basics
            WHERE start_year > 2025;          
""")
conn.commit()

In [ ]:
# Movie_ratings table
pd.read_sql(""" 
            SELECT *
            FROM movie_ratings
            LIMIT 10;   
""", conn)

In [ ]:
# check for missing values
pd.read_sql("""SELECT *
                FROM movie_ratings
                WHERE movie_id IS NULL
                OR averagerating IS NULL
                OR numvotes IS NULL;
""", conn)

In [ ]:
# Checking ranges in the numeric columns
pd.read_sql("""
    SELECT 
           MIN(averagerating) AS min_rating,
           MAX(averagerating) AS max_rating,
           MIN(numvotes) AS min_votes,
           MAX(numvotes) AS max_votes
    FROM movie_ratings;
""", conn)

In [ ]:
# Remove rows with extremely low votes
cur.execute("""
            DELETE FROM movie_ratings
            WHERE numvotes < 100;          
""")
conn.commit()

### 2.0 Exploratory Data Analysis
### 2.1 Performance of genres based on the rating
Rate score can show how much the movie was liked.

The genres are merged to have one genre individually rather than the grouped genres

In [ ]:
# Merge the movie_basics and movie_ratings tables
cur.execute("""
            CREATE TABLE imdb_merged AS
            SELECT 
                b.movie_id,
                b.primary_title,
                b.original_title,
                b.start_year,
                b.runtime_minutes,
                b.genres,
                r.averagerating,
                r.numvotes
            FROM movie_basics AS b
            INNER JOIN movie_ratings AS r
            ON b.movie_id = r.movie_id;
""")
conn.commit()

In [ ]:
# Preview merged data
pd.read_sql("""
        SELECT * FROM imdb_merged LIMIT 5;
""", conn)

In [ ]:
pd.read_sql("""SELECT name FROM sqlite_master WHERE type='table';""",conn)

In [ ]:
# Duplicate dataframe and split multi-genre entries
imdb_merged = pd.read_sql("SELECT * FROM imdb_merged;", conn)


imdb_genre = imdb_merged.copy()
imdb_genre['genre_split'] = imdb_genre['genres'].str.split(',')

# Explode genres (so one genre per row)
imdb_genre = imdb_genre.explode('genre_split')

# Compute average, median and count of ratings per genre
genre_ratings = (
    imdb_genre.groupby('genre_split', as_index=False)
    .agg(
        avg_rating=('averagerating', lambda x: round(x.mean(), 2)),
        median_rating=('averagerating', lambda x: round(x.median(), 2)),
        total_votes=('numvotes', 'sum'),
        movie_count=('primary_title', 'count')
    )
    .sort_values(by='avg_rating', ascending=False)
)

# Display results
print(genre_ratings.head(10))

In [ ]:
print(genre_ratings.tail(10))

In [ ]:
# Visual representation of the top 10 rated genres

# top 10 genres by average rating
top10_genres = genre_ratings.head(10)

# Plot
plt.figure(figsize=(12,6))
plt.bar(top10_genres['genre_split'], top10_genres['avg_rating'], color='blue')
plt.xlabel('Genre')
plt.ylabel('Average Rating')
plt.title('Top 10 Genres by Average Rating')
plt.show()

The graph shows that News, Documentary and Biography are the top-rated genres on average, with News having the highest average rating of 7.13. 
This suggests that audiences tend to favor movies in these genres in terms of quality. 
Genres like Reality_TV, Horror and Adult while popular, have slightly lower average ratings among the top 10.

### 2.2 Performance of genre based on popularity(number of votes)
The number of votes could be used to determine the votes with a bigger audience or more popular

In [ ]:
# Average number of votes per genre
imdb_genre[imdb_genre['movie_id']=='tt0100275']

average_votes = (
    imdb_genre.groupby('genre_split', as_index=False)
    .agg(
        avg_votes=('numvotes', lambda x: round(x.mean(), 2)),
        movie_count=('primary_title', 'count'),
        avg_rating=('averagerating', lambda x: round(x.mean(), 2))
    )
    .sort_values(by='avg_votes', ascending=False)
)
print("Top 5 with highest average votes")
print(average_votes.head())
print("---------------------------------")
print("Top 5 with lowest average votes")
print(average_votes.tail())

In [ ]:
# Visual representation of the top 10 popular genres

# top 10 genres by highest vote count
top10_popular_genres = average_votes.head(10)

# Plot
plt.figure(figsize=(10,6))
plt.bar(top10_popular_genres['genre_split'], top10_popular_genres['avg_votes'], color='blue')
plt.xlabel('Genre')
plt.ylabel('Average Votes')
plt.title('Top 10 Popular Genres by Average Votes')
plt.show()

Genres like Adventure, Sci-Fi and Fantasy dominate audience attention and generate the highest average votes per movie.
Genres like Documentary are have low average votes or have smaller audiences even if there are many movies.
This can guide studios on which genres have both high engagement and high potential for audience reach.
The studio can balance high-reach genres with niche genres to diversify content and capture both mass and loyal niche audiences.

In [ ]:

# Total votes per genre
total_votes_genre = (
    imdb_genre.groupby('genre_split', as_index=False)
    .agg(
        total_votes=('numvotes', 'sum'),
        movie_count=('primary_title', 'count')
    )
)
print(total_votes_genre.head())

# Scatter plot 

plt.figure(figsize=(8,6))
sns.scatterplot(x='movie_count', y='total_votes', data=total_votes_genre)
plt.xlabel('Number of Movies')
plt.ylabel('Total Votes')
plt.title('Association between Number of Movies & Total Votes per Genre')
plt.show()

In [ ]:
correlation = total_votes_genre['movie_count'].corr(total_votes_genre['total_votes'])
print(f"Correlation between movie count and total votes: {correlation:.2f}")

In [ ]:
### There is a strong positive relationship between the number of movies and the number of votes
### This means that the number of movies produced influence the number of votes.

### 2.3 To analyze film performance across studios, years and domestic versus international markets
Studio Performance in terms of revenue

In [ ]:
bom.head()

In [ ]:
bom.describe()

In [ ]:
# Grouped studios with the number of movies produced
top_studios = bom['studio'].value_counts()
print("The top 5 studios by count:")
print(top_studios.head())

In [ ]:
# Calculate the total gross and add column for total gross to millions for easy understanding
bom['total_gross'] = bom['domestic_gross'] + bom['foreign_gross']
bom['total_gross_millions'] =bom['total_gross']/1000000
bom.head()

In [ ]:
# Grouped studios with the mean total gross
studio_analysis = bom.groupby('studio')['total_gross_millions'].agg(
    ['mean', 'median', 'count']).sort_values(by='mean', ascending=False)
studio_analysis.head(10)

In [ ]:
bom[bom['studio']== 'HC']

In [ ]:
bom[bom['studio']== 'GrtIndia']

In [ ]:
#Check if some studios perform significantly better (higher gross) than others.
# One-way ANOVA
from scipy.stats import f_oneway

# Ho: The mean gross is the same across all studios.
# H1: At least one studio has a significantly different mean gross.


groups = [group['total_gross'] for name, group in bom.groupby('studio')]
f_stat, p = f_oneway(*groups)
print(f"F-statistic: {f_stat:.3f}, P-value: {p:.3f}")

#Reject Ho since p_value(0.00) < than 0.05
'''
Atleast one studio has a difference in the mean if the gross income
The type of films the best performing studios produce have a higher income
'''

Year performance in terms of revenue collected which imply the trends

In [ ]:
# Grouped year with the mean total gross
year_analysis = bom.groupby('year')['total_gross_millions'].agg(
    ['mean', 'median', 'count']).sort_values(by='mean', ascending=False)
year_analysis.head(10)

In [ ]:
yearly_gross = bom.groupby('year', as_index=False)['total_gross_millions'].sum()

plt.figure(figsize=(8,6))
plt.plot(yearly_gross['year'], yearly_gross['total_gross_millions'], label='Total Gross', color='blue')
plt.title("Total Gross Income Over Years")
plt.xlabel("Year")
plt.ylabel("Total Gross in Million Dollars")
plt.xticks(yearly_gross['year'])  # ensures all years are shown
plt.legend()
plt.grid(True)
plt.show()

The high performance in 2016 and 2017 suggests that the industry is still capable of generating massive revenue

In [ ]:
# Check if average film gross has changed significantly over time (e.g., trends).
# One-way ANOVA.

# Ho: Average gross has not changed across years.
# H1: Average gross differs across years.

groups = [group['total_gross'] for name, group in bom.groupby('year')]
f_stat, p = f_oneway(*groups)
print(f"F-statistic: {f_stat:.3f}, P-value: {p:.3f}")

# Reject Ho since p_value(0.00) < than 0.05

'''
Atleast one year has a difference in the mean if the gross income.
Focus on the most profitable years and examine what genres or themes dominated them.
'''

#### Hypothesis Testing
Using the alpha(confidence level) = 0.05

##### Using Pearsons correlation to Check relationship between domestic gross and foreign gross.

In [ ]:
# Correlation between domestic and foreign

# Ho: There is no linear relationship between domestic and foreign gross.
# H1: There is a significant linear relationship between domestic and foreign gross.
from scipy import stats
from scipy.stats import pearsonr

r, p_value = pearsonr(bom['domestic_gross'], bom['foreign_gross'])

print(f"Correlation coefficient (r): {r:.3f}")
print(f"P-value: {p_value:.3f}")

 # When the p_value is < 0.05 Reject the Null Hypothesis

In [ ]:
# Heatmap to show correlation between domestic and foreign gross
corr= bom[['domestic_gross', 'foreign_gross']].corr()
sns.heatmap(corr, annot=True,vmin=-1, vmax=1)
plt.title("Correlation between  domestic and foreign gross")
plt.show()

In [ ]:
"""
There is a strong positive correlation between domestic and foreign market
The null hypothesis is rejected indicating there is a linear relationship between domestic gross and foreign gross

The studio can safely assume that films successful locally are likely to perform well internationally 
Investment in global marketing can increase profit.
"""

In [ ]:
# Plot to show the relationship between domestic and foreign income
plt.figure(figsize=(8,6))
# sns.scatterplot(data=bom, x='domestic_gross', y='foreign_gross',color='darkblue')
sns.regplot(data= bom, x='domestic_gross', y='foreign_gross', color='blue')
plt.show()

In [ ]:
# Perform a paired ttest to compare the means between the domestic and foreign income

#Ho: There is no difference in means between the domestic and foreign income (mean domestic == mean foreign)
#H1: There is a difference in means between the domestic and foreign income (mean domestic != mean foreign)

t_stat, p_val = stats.ttest_rel(bom['domestic_gross'], bom['foreign_gross'])
print(f"T-Statistic: {t_stat:.3f}, P-Value: {p_val:.3f}")

# When p_value is < 0.05 Reject the Null Hypothesis
'''
In conclusion there is a difference in means between domestic and foreign gross.
Technically one earns more.
'''

In [ ]:
bom[['domestic_gross', 'foreign_gross']].mean()

'''
The foreign gross technically earns higher!
'''

In [ ]:
# bom=bom.drop(columns=['log_domestic_gross', 'log_foreign_gross', 'difference'], axis=1)

In [ ]:
sns.pairplot(bom)

### 3.0 Conclusion
In conclusion, the datasets used are the im.db dataset and the box office mojo(bom.movie_gross.csv) dataset to conduct the analysis.
1. **Based on the rating:**  
    News, Documentary and Biography are the top-rated genres on average, suggesting that audiences tend to favor movies in these genres in terms of quality. Genres like Reality_TV, Horror and Adult while popular, have slightly lower average ratings.

2. **Based of popularity:**  
    Adventure, Sci-Fi and Fantasy genres dominate audience attention and generate the highest average votes per movie.Genres like Documentary are have low average votes or have smaller audiences even if there are many movies.
    This can guide studios on which genres have both high engagement and high potential of audience reach.
    Though the number of votes is highly influenced by the number of movies in the genre with a corr=(0.7).

3. **Based on the income generation:**  
    An ANOVA test confirmed that there is a significant difference in mean gross income among film studios, meaning certain studios consistently outperform others financially. Benchmarking the HC(Hallmark), P/DW(Paramount DreamWorks) to see the type of films they produce thus their high income is a great strategy to determine the best films to invest in.

    There is a strong positive correlation (0.79) between domestic gross and foreign gross.A film that is successful in the domestic market is highly likely to perform well internationally. Investing in global marketing for films that perform well domestically is a strong strategy to increase overall profit.

    There is also an upward trend in the gross total income of the movies over the years suggesting that the studio is likey to make profit.